"""Add pitch_variation_percent to Upload

Revision ID: 073680f108a8
Revises: 792acba7c559
Create Date: 2025-07-16 04:25:37.863093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '073680f108a8'
down_revision: Union[str, None] = '792acba7c559'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upload', sa.Column('pitch_variation_percent', sa.Integer(), nullable=True))
    # op.alter_column('upload', 'pitch_std',
    #            existing_type=sa.REAL(),
    #            type_=sa.Float(),
    #            existing_nullable=True)
    # op.alter_column('upload', 'pitch_mean',
    #            existing_type=sa.REAL(),
    #            type_=sa.Float(),
    #            existing_nullable=True)
    # op.alter_column('upload', 'volume_mean',
    #            existing_type=sa.REAL(),
    #            type_=sa.Float(),
    #            existing_nullable=True)
    # op.alter_column('upload', 'volume_std',
    #            existing_type=sa.REAL(),
    #            type_=sa.Float(),
    #            existing_nullable=True)
    # op.alter_column('upload', 'noise_level',
    #            existing_type=sa.REAL(),
    #            type_=sa.Float(),
    #            existing_nullable=True)
    # op.alter_column('upload', 'vocab_richness',
    #            existing_type=sa.REAL(),
    #            type_=sa.Float(),
    #            existing_nullable=True)
    # op.alter_column('upload', 'sentence_var',
    #            existing_type=sa.REAL(),
    #            type_=sa.Float(),
    #            existing_nullable=True)
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('upload', 'sentence_var',
    #            existing_type=sa.Float(),
    #            type_=sa.REAL(),
    #            existing_nullable=True)
    # op.alter_column('upload', 'vocab_richness',
    #            existing_type=sa.Float(),
    #            type_=sa.REAL(),
    #            existing_nullable=True)
    # op.alter_column('upload', 'noise_level',
    #            existing_type=sa.Float(),
    #            type_=sa.REAL(),
    #            existing_nullable=True)
    # op.alter_column('upload', 'volume_std',
    #            existing_type=sa.Float(),
    #            type_=sa.REAL(),
    #            existing_nullable=True)
    # op.alter_column('upload', 'volume_mean',
    #            existing_type=sa.Float(),
    #            type_=sa.REAL(),
    #            existing_nullable=True)
    # op.alter_column('upload', 'pitch_mean',
    #            existing_type=sa.Float(),
    #            type_=sa.REAL(),
    #            existing_nullable=True)
    # op.alter_column('upload', 'pitch_std',
    #            existing_type=sa.Float(),
    #            type_=sa.REAL(),
    #            existing_nullable=True)
    # op.drop_column('upload', 'pitch_variation_percent')
    pass
    # ### end Alembic commands ###
