"""Add pitch_label to Upload

Revision ID: 792acba7c559
Revises: 69f37cc2e135
Create Date: 2025-07-16 03:56:30.097539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '792acba7c559'
down_revision: Union[str, None] = '69f37cc2e135'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('upload', sa.Column('pitch_label', sa.String(length=64), nullable=True))
    # op.alter_column('upload', 'pitch_std',
    #            existing_type=sa.REAL(),
    #            type_=sa.Float(),
    #            existing_nullable=True)
    # op.alter_column('upload', 'pitch_mean',
    #            existing_type=sa.REAL(),
    #            type_=sa.Float(),
    #            existing_nullable=True)
    # op.alter_column('upload', 'volume_mean',
    #            existing_type=sa.REAL(),
    #            type_=sa.Float(),
    #            existing_nullable=True)
    # op.alter_column('upload', 'volume_std',
    #            existing_type=sa.REAL(),
    #            type_=sa.Float(),
    #            existing_nullable=True)
    # op.alter_column('upload', 'noise_level',
    #            existing_type=sa.REAL(),
    #            type_=sa.Float(),
    #            existing_nullable=True)
    # op.alter_column('upload', 'vocab_richness',
    #            existing_type=sa.REAL(),
    #            type_=sa.Float(),
    #            existing_nullable=True)
    # op.alter_column('upload', 'sentence_var',
    #            existing_type=sa.REAL(),
    #            type_=sa.Float(),
    #            existing_nullable=True)
    # ### end Alembic commands ###
    pass


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('upload', 'sentence_var',
    #            existing_type=sa.Float(),
    #            type_=sa.REAL(),
    #            existing_nullable=True)
    # op.alter_column('upload', 'vocab_richness',
    #            existing_type=sa.Float(),
    #            type_=sa.REAL(),
    #            existing_nullable=True)
    # op.alter_column('upload', 'noise_level',
    #            existing_type=sa.Float(),
    #            type_=sa.REAL(),
    #            existing_nullable=True)
    # op.alter_column('upload', 'volume_std',
    #            existing_type=sa.Float(),
    #            type_=sa.REAL(),
    #            existing_nullable=True)
    # op.alter_column('upload', 'volume_mean',
    #            existing_type=sa.Float(),
    #            type_=sa.REAL(),
    #            existing_nullable=True)
    # op.alter_column('upload', 'pitch_mean',
    #            existing_type=sa.Float(),
    #            type_=sa.REAL(),
    #            existing_nullable=True)
    # op.alter_column('upload', 'pitch_std',
    #            existing_type=sa.Float(),
    #            type_=sa.REAL(),
    #            existing_nullable=True)
    # op.drop_column('upload', 'pitch_label')
    # ### end Alembic commands ###
    pass
